#!/bin/bash
#
# /usr/lib/cups/backend/fiscal
#
# (c) 2015  Alejandro Vilar <alevilar@gmail.com>
#   
#
# License: GNU GPLv2 or GPLv3 (your choice)
# Warranty: None at all; you may need to fix included defects on your own.
#
 
 backend=${0}
 jobid=${1}
 cupsuser=${2}
 jobtitle=${3}
 jobcopies=${4}
 joboptions=${5}
 jobfile=${6}
 
 # the following messages should appear in /var/log/cups/error_log,
 # depending on what "LogLevel" setting your cupsd.conf carries:
 echo "INFO: backend=${backend}"       1>&2
 echo "INFO: jobid=${jobid}"           1>&2
 echo "INFO: cupsuser=${cupsuser}"     1>&2
 echo "INFO: jobtitle=${jobtitle}"     1>&2
 echo "INFO: jobcopies=${jobcopies}"   1>&2
 echo "INFO: joboptions=${joboptions}" 1>&2
 echo "INFO: jobfile=${jobfile}"       1>&2
 echo "INFO: printtime=${printtime}"   1>&2
 # echo "EMERG:  This is a \"emergency\" level log message" 1>&2
 # echo "ALERT:  This is a \"alert\" level log message"     1>&2
 # echo "CRIT:   This is a \"critical\" level log message"  1>&2
 # echo "ERROR:  This is a \"error\" level log message"     1>&2
 # echo "WARN:   This is a \"warn\" level log message"      1>&2
 # echo "NOTICE: This is a \"notice\" level log message"    1>&2
 # echo "INFO:   This is a \"info\" level log message"      1>&2
 # echo "INFO:   This is a 2nd \"info\" level log message"  1>&2
 # echo "INFO:   This is a 3rd \"info\" level log message"  1>&2
 # echo "DEBUG:  This is a \"debug\" level log message"     1>&2
                                                                                                           
 
 # we will read the output filename from the printers $DEVICE_URI environment
 # variable that should look s.th. like "fiscal:/tty"
 
 # Now do the real work:
 case ${#} in
       0)
          # this case is for "backend discovery mode"
          #echo "serial serial:/dev/ttyS0?baud=115200"
          if [ -f /dev/fiscalprinter ];
		  then
          	echo "direct fiscal \"fiscal:fiscalprinter\" \"Direct Fiscal Printing para Impresoras Fiscales\""
		  else
		  	echo "direct fiscal \"Unknown\" \"Direct Fiscal Printing para Impresoras Fiscales\""
		  fi
        
          exit 0
          ;;
       5)
          # backend needs to read from stdin if number of arguments is 5
          cat - > /tmp/tmp_fiscal
          mkdir -p /tmp/cups_spooler
          echo "INFO: lo mande a guardar desde STDIN"   1>&2
          cd /tmp
          rm /tmp/spooler_log
          SP=`spooler -p${DEVICE_URI#fiscal:} -f /tmp/tmp_fiscal -e -l -d /tmp/cups_spooler/cupsspooler.log -n -b /tmp/cups_spooler`
          if [ -n "$SP" ]; then
          	echo "ERROR: spooler dice: $SP"   1>&2
		  fi
          $RETINF=`cat /tmp/cups_spooler/cupsspooler.log`
          echo "INFO: $RETINF"   1>&2
          rm /tmp/tmp_fiscal
          rm -R /tmp/cups_spooler/*
          ;;
       6)
            # backend needs to read from file if number of arguments is 6
          echo "INFO: lo mande a guardar directo desde el archivo que vino como job"   1>&2
          mkdir -p /tmp/cups_spooler
          rm /tmp/cups_spooler/cupsspooler.log
      	  SP=`spooler -p${DEVICE_URI#fiscal:} -f ${6}  -e -l -n -b /tmp/cups_spooler` 
          if [ -n "$SP" ]; then
          	echo "ERROR: spooler dice: $SP"   1>&2
		  fi
          $RETINF=`cat /tmp/cups_spooler/cupsspooler.log`
          echo "INFO: el Log dice: $RETINF"   1>&2
         
          ;;
       1|2|3|4|*)
          # these cases are unsupported
          echo " "
          echo " Usage: fiscal job-id user title copies options [file]"
          echo " "
          echo " (Install as CUPS backend in /usr/lib/cups/backend/fiscal)"
          echo " (Use as 'device URI' like \"fiscal:/ttyS0\" for printer installation.)"
          exit 0
 esac
 
 echo  1>&2
 
 # we reach this line only if we actually "printed something"
 echo "NOTICE: processed Job ${jobid} to file ${DEVICE_URI#fiscal:}" 1>&2
 echo "NOTICE: End of \"${0}\" run...."                             1>&2
 echo "NOTICE: ---------------------------------------------------" 1>&2
 echo  1>&2
 exit 0
 
 ################# end "2file" #############################################